# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: clip_text.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='clip_text.proto',
  package='rpc_package',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0f\x63lip_text.proto\x12\x0brpc_package\"\x1d\n\ntext_input\x12\x0f\n\x07my_text\x18\x01 \x01(\t\"\x1e\n\x0ctext_feature\x12\x0e\n\x06s_list\x18\x01 \x03(\x02\x32\x65\n\x0f\x43lipTextService\x12R\n\x1a\x66unction_operate_clip_text\x12\x17.rpc_package.text_input\x1a\x19.rpc_package.text_feature\"\x00\x62\x06proto3'
)




_TEXT_INPUT = _descriptor.Descriptor(
  name='text_input',
  full_name='rpc_package.text_input',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='my_text', full_name='rpc_package.text_input.my_text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=61,
)


_TEXT_FEATURE = _descriptor.Descriptor(
  name='text_feature',
  full_name='rpc_package.text_feature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='s_list', full_name='rpc_package.text_feature.s_list', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=93,
)

DESCRIPTOR.message_types_by_name['text_input'] = _TEXT_INPUT
DESCRIPTOR.message_types_by_name['text_feature'] = _TEXT_FEATURE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

text_input = _reflection.GeneratedProtocolMessageType('text_input', (_message.Message,), {
  'DESCRIPTOR' : _TEXT_INPUT,
  '__module__' : 'clip_text_pb2'
  # @@protoc_insertion_point(class_scope:rpc_package.text_input)
  })
_sym_db.RegisterMessage(text_input)

text_feature = _reflection.GeneratedProtocolMessageType('text_feature', (_message.Message,), {
  'DESCRIPTOR' : _TEXT_FEATURE,
  '__module__' : 'clip_text_pb2'
  # @@protoc_insertion_point(class_scope:rpc_package.text_feature)
  })
_sym_db.RegisterMessage(text_feature)



_CLIPTEXTSERVICE = _descriptor.ServiceDescriptor(
  name='ClipTextService',
  full_name='rpc_package.ClipTextService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=95,
  serialized_end=196,
  methods=[
  _descriptor.MethodDescriptor(
    name='function_operate_clip_text',
    full_name='rpc_package.ClipTextService.function_operate_clip_text',
    index=0,
    containing_service=None,
    input_type=_TEXT_INPUT,
    output_type=_TEXT_FEATURE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CLIPTEXTSERVICE)

DESCRIPTOR.services_by_name['ClipTextService'] = _CLIPTEXTSERVICE

# @@protoc_insertion_point(module_scope)
